DIMENSION_COLUMNS = {
    'Region',
    'Market',
    'Year',
    'Category',
    'Segment Macro',
    'Brand',
    'Macro Channel',
    'Channel',
}

ESSENTIAL_COLUMNS = DIMENSION_COLUMNS.union({'Budget (USD)'})

RAW_REGION_COLUMN_NAME = 'Region'
HARMONIZED_REGION_COLUMN_NAME = 'Harmonized_Region'
RAW_TO_HARMONIZED_REGION_NAME_MAPPING = {
    'AED': 'AFRICA-EURASIA',
    'APAC': 'ASIA-PACIFIC',
    'EUROPE': 'EUROPE',
    'LATAM': 'LATIN AMERICA',
    'NA': 'NORTH AMERICA',
}
HILLS_REGION_NAME = 'HILLS'
EXPECTED_REGION_COLUMN_VALUES = list(RAW_TO_HARMONIZED_REGION_NAME_MAPPING.keys())
EXPECTED_HARMONIZED_REGION_COLUMNS_VALUES = EXPECTED_REGION_COLUMN_VALUES + [HILLS_REGION_NAME]





