load_country_metadata = """
SELECT 
    [CP_COUNTRY_ID],[COUNTRY_KEY],[COUNTRY_NAME],[GM_COUNTRY_ID],[HUB_ID],[HUB_KEY],[HUB_TEXT],[SUBDIVISION_ID],
    [SUBDIVISION_KEY],[SUBDIVISION_TEXT],[DIVISION_ID],[DIVISION_KEY],[DIVISION_TEXT],[ADD_DATE] 
FROM [DM_1219_ColgateGlobal].[dbo].[CP_DIM_COUNTRY]
"""
