DATABASE = "[DM_1219_ColgateGlobal].[dbo]"

all_mappings = """
SELECT  A.GM_COUNTRY_NAME
       ,A.GM_ADVERTISER_NAME
       ,A.GM_SECTOR_NAME
       ,A.GM_SUBSECTOR_NAME
       ,A.GM_CATEGORY_NAME
       ,A.GM_BRAND_NAME
       ,A.GM_PRODUCT_NAME
       ,A.CP_SUBCATEGORY_ID
       ,A.CP_SUBCATEGORY_NAME
       ,A.CP_VARIANT_ID_1PH
       ,A.CP_VARIANT_NAME
FROM {}.GM_CP_MASTER_PRODUCT_MAPPING AS A
""".format(DATABASE)

