DATABASE = "[dbo]"
TABLE = "[GM_CP_MASTER_PRODUCT_MAPPING]"

all_mappings_q = """
SELECT  GM_COUNTRY_NAME
       ,GM_ADVERTISER_NAME
       ,GM_SECTOR_NAME
       ,GM_SUBSECTOR_NAME
       ,GM_CATEGORY_NAME
       ,GM_BRAND_NAME
       ,GM_PRODUCT_NAME
       ,CP_SUBCATEGORY_ID
       ,CP_SUBCATEGORY_NAME
       ,CP_VARIANT_ID_1PH
       ,CP_VARIANT_NAME
FROM {}.{}
""".format(DATABASE, TABLE)
# WHERE
# (ABS(CAST(
#   (BINARY_CHECKSUM(*) * RAND()) as int)) % 100) < 70

mapped_subcategories_q = """
SELECT
GM_GLOBAL_PRODUCT_ID
,GM_COUNTRY_ID
,GM_COUNTRY_NAME
,GM_ADVERTISER_NAME
,GM_SECTOR_NAME
,GM_SUBSECTOR_NAME
,GM_CATEGORY_NAME
,GM_BRAND_NAME
,GM_PRODUCT_NAME
,SOS_PRODUCT
,CP_SUBCATEGORY_ID
,CP_SUBCATEGORY_NAME
,CP_VARIANT_ID_1PH
,CP_BRAND_ID
,CP_BRAND_NAME
,LAST_MAPPED_BY
FROM {}.{}
WHERE
CP_SUBCATEGORY_NAME IS NOT NULL
AND 
(ABS(CAST(
  (BINARY_CHECKSUM(*) * RAND()) as int)) % 100) < 70
""".format(DATABASE, TABLE)

unmapped_subcategories_q = """
SELECT
GM_GLOBAL_PRODUCT_ID
,GM_COUNTRY_ID
,GM_COUNTRY_NAME
,GM_ADVERTISER_NAME
,GM_SECTOR_NAME
,GM_SUBSECTOR_NAME
,GM_CATEGORY_NAME
,GM_BRAND_NAME
,GM_PRODUCT_NAME
,SOS_PRODUCT
,CP_SUBCATEGORY_ID
,CP_SUBCATEGORY_NAME
,CP_VARIANT_ID_1PH
,CP_BRAND_ID
,CP_BRAND_NAME
,LAST_MAPPED_BY
FROM {}.{}
WHERE 
CP_SUBCATEGORY_NAME IS NULL
""".format(DATABASE, TABLE)

distinct_subcat_name_and_id_q = """
SELECT DISTINCT CP_SUBCATEGORY_ID, CP_SUBCATEGORY_NAME
FROM {}.{}
WHERE
CP_SUBCATEGORY_ID IS NOT NULL
""".format(DATABASE, TABLE)

mapped_nonsos_variants_q = """
SELECT
GM_GLOBAL_PRODUCT_ID
,GM_COUNTRY_ID
,GM_COUNTRY_NAME
,GM_ADVERTISER_NAME
,GM_SECTOR_NAME
,GM_SUBSECTOR_NAME
,GM_CATEGORY_NAME
,GM_BRAND_NAME
,GM_PRODUCT_NAME
,SOS_PRODUCT
,CP_CATEGORY_NAME
,CP_SUBCATEGORY_ID
,CP_SUBCATEGORY_NAME
,CP_BRAND_ID
,CP_BRAND_NAME
,CP_SUBBRAND_NAME
,CP_VARIANT_ID_1PH
,CP_VARIANT_NAME
,LAST_MAPPED_BY
FROM {}.{}
WHERE 
(ABS(CAST(
  (BINARY_CHECKSUM(*) * RAND()) as int)) % 100) < 70
AND
CP_VARIANT_NAME IS NOT NULL AND SOS_PRODUCT='0' 
""".format(DATABASE, TABLE)

mapped_sos_variants_q = """
SELECT
GM_GLOBAL_PRODUCT_ID
,GM_COUNTRY_ID
,GM_COUNTRY_NAME
,GM_ADVERTISER_NAME
,GM_SECTOR_NAME
,GM_SUBSECTOR_NAME
,GM_CATEGORY_NAME
,GM_BRAND_NAME
,GM_PRODUCT_NAME
,SOS_PRODUCT
,CP_CATEGORY_NAME
,CP_SUBCATEGORY_ID
,CP_SUBCATEGORY_NAME
,CP_BRAND_ID
,CP_BRAND_NAME
,CP_SUBBRAND_NAME
,CP_VARIANT_ID_1PH
,CP_VARIANT_NAME
,LAST_MAPPED_BY
FROM {}.{}
WHERE 
(ABS(CAST(
  (BINARY_CHECKSUM(*) * RAND()) as int)) % 100) < 70
AND 
CP_VARIANT_NAME IS NOT NULL AND SOS_PRODUCT='1' 
""".format(DATABASE, TABLE)

