-- INV

UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [ADVERTISER] = UPPER(LTRIM(RTRIM([ADVERTISER])))
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [CATEGORY] = UPPER(LTRIM(RTRIM([CATEGORY])))
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [BRAND] = UPPER(LTRIM(RTRIM([BRAND])))
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [PRODUCT] = UPPER(LTRIM(RTRIM([PRODUCT])))
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [SECTOR] = UPPER(LTRIM(RTRIM([SECTOR])))
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [SUBSECTOR] = UPPER(LTRIM(RTRIM([SUBSECTOR])))
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [MEDIA] = UPPER(LTRIM(RTRIM([MEDIA])))
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [SECTOR] = 'N/A' WHERE [SECTOR] IS NULL OR [SECTOR] = ''
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [SUBSECTOR] = 'N/A' WHERE [SUBSECTOR] IS NULL OR [SUBSECTOR] = ''
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [CATEGORY] = 'N/A' WHERE [CATEGORY] IS NULL OR [CATEGORY] = ''
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [ADVERTISER] = 'N/A' WHERE [ADVERTISER] IS NULL OR [ADVERTISER] = ''
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [BRAND] = 'N/A' WHERE [BRAND] IS NULL OR [BRAND] = ''
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [PRODUCT] = 'N/A' WHERE [PRODUCT] IS NULL OR [PRODUCT] = ''
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [NETWORK] = 'N/A' WHERE [NETWORK] IS NULL OR [NETWORK] = ''
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [VEHICLE] = 'N/A' WHERE [VEHICLE] IS NULL OR [VEHICLE] = ''
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [DAYPART] = 'N/A' WHERE [DAYPART] IS NULL OR [DAYPART] = ''
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [CREATIVE] = 'N/A' WHERE [CREATIVE] IS NULL OR [CREATIVE] = ''
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [FORMAT] = 'N/A' WHERE [FORMAT] IS NULL OR [FORMAT] = ''
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [MEDIA] = 'N/A' WHERE [MEDIA] IS NULL OR [MEDIA] = ''
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [TOTAL_DURATION] = 0 WHERE [TOTAL_DURATION] IS NULL OR [TOTAL_DURATION] = '' OR  [TOTAL_DURATION] LIKE'N/A'
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [LOCAL_SPEND] = 0 WHERE [LOCAL_SPEND] IS NULL OR [LOCAL_SPEND] = ''
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [GRP] = 0 WHERE [GRP] IS NULL OR [GRP] = ''
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [INSERTIONS] = 0 WHERE [INSERTIONS] IS NULL OR [INSERTIONS] = '' OR  [INSERTIONS] LIKE'N/A'
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [SPOT_LENGTH] = 0 WHERE [SPOT_LENGTH] IS NULL OR [SPOT_LENGTH] = '' OR  [SPOT_LENGTH] LIKE'N/A'
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [SUBMEDIA_1] = 'N/A' WHERE [SUBMEDIA_1] IS NULL OR [SUBMEDIA_1] = ''
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [SUBMEDIA_2] = 'N/A' WHERE [SUBMEDIA_2] IS NULL OR [SUBMEDIA_2] = ''
UPDATE A
	SET A.BRAND = RTRIM(SUBSTRING(BRAND, 1, CHARINDEX('/', BRAND) - 1))
FROM [STG].[Raw_Data_CHM_INV_STG] A
UPDATE A
	SET A.PRODUCT = Rtrim(Substring([Product], 1, Charindex('/', [Product]) - 1))
FROM [STG].[Raw_Data_CHM_INV_STG] A
UPDATE A
	SET A.PRODUCT_CHM = Ltrim(RIGHT(PRODUCT_CHM, Len(PRODUCT_CHM) - Charindex('/', PRODUCT_CHM)))
FROM [STG].[Raw_Data_CHM_INV_STG] A
UPDATE A
	SET A.MARKET = Ltrim(Rtrim(Substring(A.MARKET, 1, Charindex('/', A.MARKET) - 1)))
FROM [STG].[Raw_Data_CHM_INV_STG] A
UPDATE [STG].[Raw_Data_CHM_INV_STG] SET [PRODUCT_CHM] = 'N/A' WHERE [PRODUCT_CHM] IS NULL OR [PRODUCT_CHM] = ''
EXEC [STG].[usp_Final_SPEND_CHM]
EXEC [STG].[usp_Final_SPEND_NonTV_CHM]


--GRP
[STG].[Raw_Data_CHM_GRP_STG]

UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [ADVERTISER] = UPPER(LTRIM(RTRIM([ADVERTISER])))
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [CATEGORY] = UPPER(LTRIM(RTRIM([CATEGORY])))
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [BRAND] = UPPER(LTRIM(RTRIM([BRAND])))
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [PRODUCT] = UPPER(LTRIM(RTRIM([PRODUCT])))
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [SECTOR] = UPPER(LTRIM(RTRIM([SECTOR])))
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [SUBSECTOR] = UPPER(LTRIM(RTRIM([SUBSECTOR])))
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [MEDIA] = UPPER(LTRIM(RTRIM([MEDIA])))
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [SECTOR] = 'N/A' WHERE [SECTOR] IS NULL OR [SECTOR] = ''
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [SUBSECTOR] = 'N/A' WHERE [SUBSECTOR] IS NULL OR [SUBSECTOR] = ''
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [CATEGORY] = 'N/A' WHERE [CATEGORY] IS NULL OR [CATEGORY] = ''
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [ADVERTISER] = 'N/A' WHERE [ADVERTISER] IS NULL OR [ADVERTISER] = ''
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [BRAND] = 'N/A' WHERE [BRAND] IS NULL OR [BRAND] = ''
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [PRODUCT] = 'N/A' WHERE [PRODUCT] IS NULL OR [PRODUCT] = ''
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [NETWORK] = 'N/A' WHERE [NETWORK] IS NULL OR [NETWORK] = ''
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [VEHICLE] = 'N/A' WHERE [VEHICLE] IS NULL OR [VEHICLE] = ''
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [DAYPART] = 'N/A' WHERE [DAYPART] IS NULL OR [DAYPART] = ''
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [CREATIVE] = 'N/A' WHERE [CREATIVE] IS NULL OR [CREATIVE] = ''
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [FORMAT] = 'N/A' WHERE [FORMAT] IS NULL OR [FORMAT] = ''
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [MEDIA] = 'N/A' WHERE [MEDIA] IS NULL OR [MEDIA] = ''
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [TOTAL_DURATION] = 0 WHERE [TOTAL_DURATION] IS NULL OR [TOTAL_DURATION] = '' OR  [TOTAL_DURATION] LIKE'N/A'
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [LOCAL_SPEND] = 0 WHERE [LOCAL_SPEND] IS NULL OR [LOCAL_SPEND] = ''
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [GRP] = 0 WHERE [GRP] IS NULL OR [GRP] = ''
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [INSERTIONS] = 0 WHERE [INSERTIONS] IS NULL OR [INSERTIONS] = '' OR  [INSERTIONS] LIKE'N/A'
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [SPOT_LENGTH] = 0 WHERE [SPOT_LENGTH] IS NULL OR [SPOT_LENGTH] = '' OR  [SPOT_LENGTH] LIKE'N/A'
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [PRODUCT_CHM] = 'N/A' WHERE [PRODUCT_CHM] IS NULL OR [PRODUCT_CHM] = ''
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [SUBMEDIA_1] = 'N/A' WHERE [SUBMEDIA_1] IS NULL OR [SUBMEDIA_1] = ''
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [SUBMEDIA_2] = 'N/A' WHERE [SUBMEDIA_2] IS NULL OR [SUBMEDIA_2] = ''
UPDATE A
	SET A.BRAND = RTRIM(SUBSTRING(BRAND, 1, CHARINDEX('/', BRAND) - 1))
FROM [STG].[Raw_Data_CHM_GRP_STG] A
UPDATE A
	SET A.PRODUCT = Rtrim(Substring([Product], 1, Charindex('/', [Product]) - 1))
FROM [STG].[Raw_Data_CHM_GRP_STG] A
UPDATE A
	SET A.PRODUCT_CHM = Ltrim(RIGHT(PRODUCT_CHM, Len(PRODUCT_CHM) - Charindex('/', PRODUCT_CHM)))
FROM [STG].[Raw_Data_CHM_GRP_STG] A
UPDATE A
	SET A.MARKET = Ltrim(Rtrim(Substring(A.MARKET, 1, Charindex('/', A.MARKET) - 1)))
FROM [STG].[Raw_Data_CHM_GRP_STG] A
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [PRODUCT] = 'N/A' WHERE [PRODUCT] = 'N'
UPDATE [STG].[Raw_Data_CHM_GRP_STG] SET [PRODUCT_CHM] = 'N/A' WHERE [PRODUCT_CHM] = 'A'
EXEC [STG].[usp_Final_TRP_CHM_Brand_SpendSplit]
EXEC [STG].[usp_Final_TRP_CHM]